Repository ghostery/ghostery-extension, pull requests merged in 2022-11, with the labels that each got.

#920 Fix never-consent scope in the popup
  extension-manifest-v2/package-lock.json
  extension-manifest-v3/package-lock.json
  extension-manifest-v3/src/pages/autoconsent/autoconsent.js
  extension-manifest-v3/src/pages/autoconsent/index.html
  extension-manifest-v3/src/pages/onboarding/index.html
  extension-manifest-v3/src/pages/options/index.html
  extension-manifest-v3/src/pages/panel/index.html
  extension-manifest-v3/src/pages/trackers-preview/index.html
  ui/src/modules/autoconsent/views/confirm.js
  ui/src/modules/autoconsent/views/home.js
  ui/src/modules/autoconsent/views/root.js
Labels: Type: Never-Consent, MV2, MV3

#916 Fix cosmetics background feature
  extension-manifest-v3/src/background/cosmetics.js
  extension-manifest-v3/src/content_scripts/cosmetics.js
Labels: MV3

#921 Update autoconsent to 3.0.1
  extension-manifest-v2/package-lock.json
  extension-manifest-v2/package.json
  extension-manifest-v3/package-lock.json
  extension-manifest-v3/package.json
Labels: Type: Never-Consent, MV2, MV3

#924 Fix autoconsent UI
  extension-manifest-v2/app/autoconsent/index.js
  extension-manifest-v2/src/background.js
  extension-manifest-v2/src/classes/Account.js
  extension-manifest-v2/src/classes/Globals.js
Labels: MV2

#903 Update the subscription badge
  extension-manifest-v2/_locales/en/messages.json
  extension-manifest-v2/app/panel/components/Header.jsx
  extension-manifest-v2/app/panel/components/HeaderMenu.jsx
  extension-manifest-v2/app/panel/components/Stats.jsx
  extension-manifest-v2/app/panel/components/StatsView.jsx
  extension-manifest-v2/app/panel/components/Subscribe.jsx
  extension-manifest-v2/app/panel/components/Subscription.jsx
  extension-manifest-v2/app/panel/components/Subscription/SubscriptionInfo.jsx
  extension-manifest-v2/app/panel/components/Subscription/SubscriptionMenu.jsx
  extension-manifest-v2/app/panel/components/Summary.jsx
  extension-manifest-v2/app/panel/index.jsx
  extension-manifest-v2/app/scss/partials/_header.scss
  extension-manifest-v2/app/scss/partials/_upgrade_banner.scss
  extension-manifest-v2/src/background.js
Labels: MV2

#919 Add sync user settings after changing never-consent perfs
  extension-manifest-v2/src/background.js
Labels: MV2

#926 Version bump + translation tweak
  extension-manifest-v2/_locales/en/messages.json
  extension-manifest-v2/manifest.json
Labels: MV2

#927 Release & autoconsent update
  extension-manifest-v2/package-lock.json
  extension-manifest-v3/package-lock.json
  extension-manifest-v3/package.json
  extension-manifest-v3/xcode/Ghostery.xcodeproj/project.pbxproj
Labels: MV2, MV3

#933 Add missing fallback
  extension-manifest-v2/src/classes/Common.js
Labels: MV2

#939 Update build instructions
  extension-manifest-v2/README.md
Labels: MV2

#940 Prepare release: update dependencies & bump version
  extension-manifest-v2/manifest.json
  extension-manifest-v2/package-lock.json
  extension-manifest-v2/package.json
Labels: MV2

#944 Downgrade linkedom to version 0.14.12 to fix a build error with webpack:
  extension-manifest-v2/package-lock.json
  extension-manifest-v2/package.json
Labels: MV2

#943 Update autoconsent to 3.0.3
  extension-manifest-v2/package-lock.json
  extension-manifest-v2/package.json
Labels: MV2

#934 Integrate WhoTracks.me reporting
  extension-manifest-v3/README.md
  extension-manifest-v3/package-lock.json
  extension-manifest-v3/package.json
  extension-manifest-v3/patches/rollup+2.79.1.patch
  extension-manifest-v3/src/background/communication.js
  extension-manifest-v3/src/background/index.js
  extension-manifest-v3/src/background/reporting.js
  extension-manifest-v3/xcode/Ghostery.xcodeproj/project.pbxproj
Labels: MV3
