Repository ghostery/ghostery-extension, pull requests merged in 2022-10, with the labels that each got.

#888 Version bump
  extension-manifest-v2/_locales/en/messages.json
  extension-manifest-v3/package-lock.json
  extension-manifest-v3/package.json
  extension-manifest-v3/src/_locales/en/messages.json
  extension-manifest-v3/xcode/Ghostery.xcodeproj/project.pbxproj
  extension-manifest-v3/xcode/Ghostery.xcodeproj/xcshareddata/xcschemes/Ghostery – Privacy Ad Blocker (iOS).xcscheme
  extension-manifest-v3/xcode/Ghostery.xcodeproj/xcshareddata/xcschemes/Ghostery – Privacy Ad Blocker (macOS).xcscheme
  ui/src/modules/onboarding/views/skip.js
Labels: MV3

#889 Update translations
  extension-manifest-v3/src/_locales/de/messages.json
  extension-manifest-v3/src/_locales/es/messages.json
  extension-manifest-v3/src/_locales/fr/messages.json
  extension-manifest-v3/src/_locales/hu/messages.json
  extension-manifest-v3/src/_locales/it/messages.json
  extension-manifest-v3/src/_locales/ja/messages.json
  extension-manifest-v3/src/_locales/ko/messages.json
  extension-manifest-v3/src/_locales/nl/messages.json
  extension-manifest-v3/src/_locales/pl/messages.json
  extension-manifest-v3/src/_locales/pt_BR/messages.json
  extension-manifest-v3/src/_locales/ru/messages.json
  extension-manifest-v3/src/_locales/zh_CN/messages.json
  extension-manifest-v3/src/_locales/zh_TW/messages.json
Labels: MV3

#895 Fixed: access tokens should also be refreshed on 10020 errors
  extension-manifest-v2/src/utils/api.js
Labels: Type: Bug, MV2

#894 Upgrade "common" library to 1.2.39
  extension-manifest-v2/package-lock.json
  extension-manifest-v2/package.json
Labels: MV2

#891 Update copy in settings
  extension-manifest-v3/src/pages/options/options.js
Labels: MV3

#897 Fix tracker preview
  extension-manifest-v2/package-lock.json
  extension-manifest-v2/package.json
Labels: Type: Bug, MV2

#904 MV2: fix metric system
  extension-manifest-v2/src/background.js
  extension-manifest-v2/src/classes/MetricsWrapper.js
Labels: Type: Bug

#910 UI tweak: the scrollbar in the settings UI is not needed in English
  extension-manifest-v2/app/scss/partials/_settings.scss
Labels: MV2

#909 Fix for the Never-Consent dialog showing up repeatedly on the same site
  extension-manifest-v2/src/modules/autoconsent.js
Labels: Type: Bug, MV2

#911 Use tldts generated domain in never-consent
  extension-manifest-v2/app/content-scripts/autoconsent.js
  extension-manifest-v2/src/modules/autoconsent.js
  extension-manifest-v3/package-lock.json
  extension-manifest-v3/package.json
  extension-manifest-v3/src/background/autoconsent.js
  extension-manifest-v3/src/content_scripts/autoconsent.js
Labels: Type: Never-Consent, MV2, MV3
