Repository ghostery/ghostery-extension, pull requests merged in 2023-05, with the labels that each got.

#1150 Fix regression in adblocker startup (.dat instead of .bytes) and improve startup
  extension-manifest-v3/src/background/adblocker.js
Labels: Type: Bug, MV3

#1154 Release v10.0.9
  extension-manifest-v3/package.json
  extension-manifest-v3/src/_locales/de/messages.json
  extension-manifest-v3/src/_locales/es/messages.json
  extension-manifest-v3/src/_locales/fr/messages.json
  extension-manifest-v3/src/_locales/it/messages.json
  extension-manifest-v3/src/_locales/ja/messages.json
  extension-manifest-v3/src/_locales/ko/messages.json
  extension-manifest-v3/src/_locales/pl/messages.json
  extension-manifest-v3/src/_locales/pt_BR/messages.json
  extension-manifest-v3/src/_locales/ru/messages.json
  extension-manifest-v3/src/_locales/zh_CN/messages.json
  extension-manifest-v3/src/_locales/zh_TW/messages.json
  extension-manifest-v3/xcode/Ghostery.xcodeproj/project.pbxproj
  package-lock.json
Labels: MV3

#1165 Release v10.0.10
  extension-manifest-v3/package.json
  extension-manifest-v3/src/_locales/en/messages.json
  extension-manifest-v3/xcode/Ghostery.xcodeproj/project.pbxproj
  package-lock.json
Labels: MV3

#1168 Update @whotracksme/webextension-packages
  extension-manifest-v3/package.json
  package-lock.json
Labels: MV3

#1172 Fix Chrome pin instruction image
  ui/src/modules/onboarding/assets/pin-extension-chrome.jpg
Labels: UI
