Repository ghostery/ghostery-extension, pull requests merged in 2023-03, with the labels that each got.

#1044 Use TrackerDB instead of BugsDB
  extension-manifest-v3/.gitignore
  extension-manifest-v3/package.json
  extension-manifest-v3/scripts/download-dnr-lists.js
  extension-manifest-v3/scripts/download-trackerdb.js
  extension-manifest-v3/src/background/tab-stats.js
  extension-manifest-v3/src/background/utils/bugs.js
  extension-manifest-v3/src/background/utils/trackerdb.js
  package-lock.json
Labels: MV3

#1049 MV3 build: download latest matching trackerDB
  extension-manifest-v3/package.json
  extension-manifest-v3/scripts/download-cosmetics.js
  extension-manifest-v3/scripts/download-trackerdb.js
  package-lock.json
Labels: MV3

#1053 MV2: learn more about startup exceptions
  extension-manifest-v2/src/background.js
  extension-manifest-v2/src/classes/ErrorReporter.js
Labels: MV2

#1055 Update locales
  extension-manifest-v2/_locales/de/messages.json
  extension-manifest-v2/_locales/en/messages.json
  extension-manifest-v2/_locales/es/messages.json
  extension-manifest-v2/_locales/fr/messages.json
  extension-manifest-v2/_locales/hu/messages.json
  extension-manifest-v2/_locales/it/messages.json
  extension-manifest-v2/_locales/ja/messages.json
  extension-manifest-v2/_locales/ko/messages.json
  extension-manifest-v2/_locales/nl/messages.json
  extension-manifest-v2/_locales/pl/messages.json
  extension-manifest-v2/_locales/pt_BR/messages.json
  extension-manifest-v2/_locales/ru/messages.json
  extension-manifest-v2/_locales/zh_CN/messages.json
  extension-manifest-v2/_locales/zh_TW/messages.json
Labels: MV2

#1065 Update hybrids with a layout system hidden attr fix
  extension-manifest-v2/package.json
  extension-manifest-v3/package.json
  package-lock.json
  ui/package.json
  ui/src/modules/onboarding/views/main.js
Labels: MV2, MV3

#1067 Sync: remove deprecated settings
  extension-manifest-v2/src/classes/Globals.js
Labels: MV2

#1069 Fix css bundle path for panel android
  extension-manifest-v2/app/templates/panel_android.html
Labels: MV2, Android

#1073 Set default browser icon area to navbar
  extension-manifest-v2/manifest.json
Labels: Firefox, MV2

#1070 Remove indexeddb fix for Safari (patched in 15.3)
  extension-manifest-v3/src/content_scripts/prevent-indexeddb-tracking/ghostery-prevent-indexeddb-tracking.js
  extension-manifest-v3/src/content_scripts/prevent-indexeddb-tracking/index.js
  extension-manifest-v3/src/manifest.firefox.json
  extension-manifest-v3/src/manifest.safari.json
Labels: MV3, Safari

#1077 Release 10.0.4
  extension-manifest-v3/package.json
  extension-manifest-v3/src/_locales/de/messages.json
  extension-manifest-v3/src/_locales/en/messages.json
  extension-manifest-v3/src/_locales/es/messages.json
  extension-manifest-v3/src/_locales/fr/messages.json
  extension-manifest-v3/src/_locales/it/messages.json
  extension-manifest-v3/src/_locales/ja/messages.json
  extension-manifest-v3/src/_locales/ko/messages.json
  extension-manifest-v3/src/_locales/pl/messages.json
  extension-manifest-v3/src/_locales/pt_BR/messages.json
  extension-manifest-v3/src/_locales/ru/messages.json
  extension-manifest-v3/src/_locales/zh_CN/messages.json
  extension-manifest-v3/src/_locales/zh_TW/messages.json
  extension-manifest-v3/xcode/Ghostery.xcodeproj/project.pbxproj
  package-lock.json
Labels: MV3

#1066 Add refresh session msg for search extension
  extension-manifest-v2/src/background.js
  extension-manifest-v3/src/background/external.js
  extension-manifest-v3/src/background/index.js
  extension-manifest-v3/src/manifest.firefox.json
Labels: MV3

#1078 Only run Never Consent on HTML pages (not XML).
  extension-manifest-v2/app/content-scripts/autoconsent.js
  extension-manifest-v3/src/content_scripts/autoconsent.js
Labels: Type: Bug, MV2, MV3

#1083 Release v10.0.5
  .github/workflows/test-extension-manifest-v2.yml
  .github/workflows/test-extension-manifest-v3.yml
  .github/workflows/test-libs.yml
  .github/workflows/test-ui.yml
  extension-manifest-v3/package.json
  extension-manifest-v3/xcode/Ghostery.xcodeproj/project.pbxproj
  package-lock.json
Labels: MV3

#1093 Reporting should also trigger for history API events
  extension-manifest-v3/src/background/reporting.js
Labels: Type: Bug, MV3

#1095 Show Enable Ghostery on new tab pages
  extension-manifest-v3/src/pages/panel/views/home.js
Labels: MV3
