Repository ghostery/ghostery-extension, pull requests merged in 2023-04, with the labels that each got.

#1089 Historical stats for new-tab extension
  extension-manifest-v3/src/background/adblocker.js
  extension-manifest-v3/src/background/alarms.js
  extension-manifest-v3/src/background/devtools.js
  extension-manifest-v3/src/background/dnr.js
  extension-manifest-v3/src/background/external.js
  extension-manifest-v3/src/background/index.js
  extension-manifest-v3/src/background/onboarding.js
  extension-manifest-v3/src/background/reporting.js
  extension-manifest-v3/src/background/stats.js
  extension-manifest-v3/src/background/trackers-preview.js
  extension-manifest-v3/src/background/utils/request.js
  extension-manifest-v3/src/background/utils/trackerdb.js
  extension-manifest-v3/src/pages/autoconsent/autoconsent.js
  extension-manifest-v3/src/pages/panel/views/company.js
  extension-manifest-v3/src/pages/panel/views/home.js
  extension-manifest-v3/src/pages/settings/components/devtools.js
  extension-manifest-v3/src/store/daily-stats.js
  extension-manifest-v3/src/store/options.js
  extension-manifest-v3/src/store/session.js
  extension-manifest-v3/src/store/tab-stats.js
  extension-manifest-v3/src/utils/indexeddb.js
  extension-manifest-v3/src/utils/shims.js
Labels: MV3

#1100 Update deps and fix vendorCopy
  extension-manifest-v2/package.json
  package-lock.json
  package.json
Labels: MV2

#1102 Set onboarding CTA button type to success
  ui/src/modules/global/components/button.js
  ui/src/modules/onboarding/views/main.js
  ui/src/modules/pages/styles.css
Labels: MV2, MV3, UI

#1107 Release 10.0.7
  extension-manifest-v2/package.json
  extension-manifest-v3/package.json
  extension-manifest-v3/src/_locales/it/messages.json
  extension-manifest-v3/src/_locales/pl/messages.json
  extension-manifest-v3/src/_locales/ru/messages.json
  extension-manifest-v3/src/_locales/zh_CN/messages.json
  extension-manifest-v3/src/_locales/zh_TW/messages.json
  extension-manifest-v3/xcode/Ghostery.xcodeproj/project.pbxproj
  package-lock.json
  package.json
  ui/package.json
Labels: MV3

#1051 MV2: replace BugDB with TrackerDB
  extension-manifest-v2/.gitignore
  extension-manifest-v2/_locales/de/messages.json
  extension-manifest-v2/_locales/en/messages.json
  extension-manifest-v2/_locales/es/messages.json
  extension-manifest-v2/_locales/fr/messages.json
  extension-manifest-v2/_locales/hu/messages.json
  extension-manifest-v2/_locales/it/messages.json
  extension-manifest-v2/_locales/ja/messages.json
  extension-manifest-v2/_locales/ko/messages.json
  extension-manifest-v2/_locales/nl/messages.json
  extension-manifest-v2/_locales/pl/messages.json
  extension-manifest-v2/_locales/pt_BR/messages.json
  extension-manifest-v2/_locales/ru/messages.json
  extension-manifest-v2/_locales/vi/messages.json
  extension-manifest-v2/_locales/zh_CN/messages.json
  extension-manifest-v2/_locales/zh_TW/messages.json
  extension-manifest-v2/app/images/panel-android/categories/extensions.svg
  extension-manifest-v2/app/images/panel/extensions.svg
  extension-manifest-v2/databases/README.md
  extension-manifest-v2/databases/bugs.json
  extension-manifest-v2/manifest.json
  extension-manifest-v2/package.json
  extension-manifest-v2/src/background.js
  extension-manifest-v2/src/classes/BugDb.js
  extension-manifest-v2/src/classes/Common.js
  extension-manifest-v2/src/classes/ConfData.js
  extension-manifest-v2/src/classes/EventHandlers.js
  extension-manifest-v2/src/utils/domainInfo.js
  extension-manifest-v2/src/utils/matcher.js
  extension-manifest-v2/test/src/BugDB.test.js
  extension-manifest-v2/test/src/BugDb.test.js
  extension-manifest-v2/test/src/Foundbugs.test.js
  extension-manifest-v2/test/utils/matcher.test.js
  extension-manifest-v2/tools/amo/build.sh
  extension-manifest-v2/tools/download-trackerdb.js
  extension-manifest-v3/package.json
  extension-manifest-v3/src/_locales/de/messages.json
  extension-manifest-v3/src/_locales/en/messages.json
  extension-manifest-v3/src/_locales/es/messages.json
  extension-manifest-v3/src/_locales/fr/messages.json
  extension-manifest-v3/src/_locales/hu/messages.json
  extension-manifest-v3/src/_locales/it/messages.json
  extension-manifest-v3/src/_locales/ja/messages.json
  extension-manifest-v3/src/_locales/ko/messages.json
  extension-manifest-v3/src/_locales/nl/messages.json
  extension-manifest-v3/src/_locales/pl/messages.json
  extension-manifest-v3/src/_locales/pt_BR/messages.json
  extension-manifest-v3/src/_locales/ru/messages.json
  extension-manifest-v3/src/_locales/vi/messages.json
  extension-manifest-v3/src/_locales/zh_CN/messages.json
  extension-manifest-v3/src/_locales/zh_TW/messages.json
  extension-manifest-v3/src/store/tab-stats.js
  package-lock.json
  ui/src/modules/global/components/icon.js
  ui/src/utils/categories.js
  ui/src/utils/labels.js
Labels: MV2

#1120 Update placeholder text
  extension-manifest-v3/src/_locales/en/messages.json
  extension-manifest-v3/src/pages/panel/views/home.js
Labels: MV3

#1119 UI: fix iframe close event
  extension-manifest-v2/package.json
  extension-manifest-v3/package.json
  package-lock.json
  ui/src/utils/iframe.js
Labels: Firefox, MV2, MV3, UI

#1122 Update iOS/macOS app copy
  extension-manifest-v3/xcode/Shared (App)/Resources/Main.html
  extension-manifest-v3/xcode/Shared (App)/StoreHelper/Products.storekit
  extension-manifest-v3/xcode/Shared (App)/views/screens/Subscriptions.swift
Labels: MV3, Safari

#1113 Use generated lists for DNR rules
  extension-manifest-v3/.gitignore
  extension-manifest-v3/package.json
  extension-manifest-v3/scripts/build.js
  extension-manifest-v3/scripts/download-dnr-lists.js
  extension-manifest-v3/scripts/download-engines.js
  extension-manifest-v3/scripts/download-engines/index.js
  extension-manifest-v3/scripts/download-engines/utils.js
  extension-manifest-v3/src/background/adblocker.js
  extension-manifest-v3/src/background/dnr.js
  extension-manifest-v3/src/background/utils/trackerdb.js
  extension-manifest-v3/src/manifest.chromium.json
  extension-manifest-v3/src/manifest.safari.json
Labels: MV3

#1140 Update WhoTracksMe preview images
  extension-manifest-v3/src/pages/settings/assets/trackers_count.svg
  extension-manifest-v3/src/pages/settings/assets/trackers_count_small.svg
  extension-manifest-v3/src/pages/settings/assets/wtm_wheel.svg
  extension-manifest-v3/src/pages/settings/assets/wtm_wheel_small.svg
  extension-manifest-v3/src/pages/settings/views/privacy.js
  extension-manifest-v3/src/pages/settings/views/whotracksme.js
  ui/src/modules/settings/components/help-image.js
Labels: MV3

#1141 Unique trackers detected in tab stats
  extension-manifest-v3/src/background/stats.js
  extension-manifest-v3/src/background/utils/trackerdb.js
  extension-manifest-v3/src/pages/panel/components/copy.js
  extension-manifest-v3/src/pages/panel/views/company.js
  extension-manifest-v3/src/pages/panel/views/home.js
  extension-manifest-v3/src/pages/panel/views/tracker-details.js
  extension-manifest-v3/src/store/tab-stats.js
  ui/src/modules/global/components/tracker-wheel.js
  ui/src/modules/panel/components/stats.js
Labels: MV2, MV3

#1145 Add monkey patch disabling adoptedStylesheets in Safari
  extension-manifest-v3/src/pages/panel/index.html
  extension-manifest-v3/src/pages/panel/index.js
  extension-manifest-v3/src/pages/panel/safari-monkey-patch.js
Labels: MV3, Safari
