Repository ghostery/ghostery-extension, pull requests merged in 2023-06, with the labels that each got.

#1179 Update deps
  extension-manifest-v2/package.json
  package-lock.json
Labels: MV2

#1177 Fix Youtube adblocking
  extension-manifest-v2/package.json
  extension-manifest-v3/package.json
  package-lock.json
Labels: Firefox, MV2

#1174 Fix errors that can happen if tabs are closed
  extension-manifest-v3/src/background/adblocker.js
  extension-manifest-v3/src/background/autoconsent.js
  extension-manifest-v3/src/background/stats.js
Labels: MV3

#1199 Release 10.0.11
  extension-manifest-v3/package.json
  extension-manifest-v3/scripts/release.sh
  extension-manifest-v3/scripts/xcode-version.js
  extension-manifest-v3/xcode/Ghostery.xcodeproj/project.pbxproj
  package-lock.json
Labels: MV3, Safari, release

#1209 Release 10.0.12
  extension-manifest-v3/package.json
  extension-manifest-v3/scripts/release.sh
  extension-manifest-v3/xcode/Ghostery.xcodeproj/project.pbxproj
  package-lock.json
Labels: MV3

#1216 Update locales
  extension-manifest-v2/_locales/en/messages.json
Labels: MV2
