Repository ghostery/ghostery-extension, pull requests merged in 2023-09, with the labels that each got.

#1277 CI: upload named artefacts only on labeled PRs
  .github/workflows/artifact-upload.yml
  extension-manifest-v3/node_modules
  extension-manifest-v3/scripts/package.sh
Labels: package

#1278 Dynamic content scripts for trackers preview and serp tracking
  extension-manifest-v3/scripts/build.js
  extension-manifest-v3/src/background/index.js
  extension-manifest-v3/src/background/serp.js
  extension-manifest-v3/src/background/trackers-preview.js
  extension-manifest-v3/src/content_scripts/trackers-preview.js
  extension-manifest-v3/src/manifest.chromium.json
  extension-manifest-v3/src/manifest.firefox.json
  extension-manifest-v3/src/manifest.safari.json
  extension-manifest-v3/src/pages/settings/views/privacy.js
  extension-manifest-v3/src/store/options.js
Labels: package

#1282 Tracker Preview: detect more Google layouts
  packages/trackers-preview/src/content_scripts/index.js
Labels: Type: Bug

#1283 Clear script artefact (license generator)
  extension-manifest-v3/node_modules
Labels: MV3

#1288 Update container queries for the trackers preview
  packages/trackers-preview/src/content_scripts/index.js
Labels: MV2, MV3

#1291 Remove click listener from notification element
  extension-manifest-v3/src/pages/panel/views/home.js
Labels: MV3

#1290 Fix clear out wheel when disabling trackers preview
  extension-manifest-v3/src/background/serp.js
  packages/trackers-preview/src/content_scripts/index.js
Labels: MV2, MV3

#1292 Fix settings layout on Android Firefox
  extension-manifest-v2/package.json
  extension-manifest-v3/package.json
  package-lock.json
  packages/ui/package.json
  packages/ui/src/modules/settings/components/layout.js
Labels: MV3

#1295 Upgrade webextension-packages library
  extension-manifest-v3/package.json
  package-lock.json
Labels: MV3

#1285 Add dynamic update to adblocker engines
  extension-manifest-v3/src/background/adblocker.js
  extension-manifest-v3/src/background/devtools.js
  extension-manifest-v3/src/background/dnr.js
  extension-manifest-v3/src/background/utils/engines.js
  extension-manifest-v3/src/background/utils/trackerdb.js
  extension-manifest-v3/src/pages/settings/components/devtools.js
  extension-manifest-v3/src/store/daily-stats.js
  extension-manifest-v3/src/store/options.js
Labels: MV3

#1318 Check cookie `expirationDate` or `session` flag to not return expired cookie
  extension-manifest-v3/src/utils/api.js
Labels: Firefox, MV3

#1276 Release 10.1.4
  extension-manifest-v3/package.json
  extension-manifest-v3/src/_locales/de/messages.json
  extension-manifest-v3/src/_locales/en/messages.json
  extension-manifest-v3/src/_locales/es/messages.json
  extension-manifest-v3/src/_locales/fr/messages.json
  extension-manifest-v3/src/_locales/it/messages.json
  extension-manifest-v3/src/_locales/ja/messages.json
  extension-manifest-v3/src/_locales/ko/messages.json
  extension-manifest-v3/src/_locales/pl/messages.json
  extension-manifest-v3/src/_locales/pt_BR/messages.json
  extension-manifest-v3/src/_locales/ru/messages.json
  extension-manifest-v3/src/_locales/zh_CN/messages.json
  extension-manifest-v3/src/_locales/zh_TW/messages.json
  extension-manifest-v3/xcode/Ghostery.xcodeproj/project.pbxproj
  package-lock.json
Labels: package
