Repository ghostery/ghostery-extension, pull requests merged in 2024-03, with the labels that each got.

#1491 Never-consent popup clean up
  extension-manifest-v2/app/autoconsent/index.js
  extension-manifest-v2/app/content-scripts/autoconsent.js
  extension-manifest-v2/app/templates/autoconsent.html
  extension-manifest-v2/manifest.json
  extension-manifest-v2/src/background.js
  extension-manifest-v2/src/classes/Account.js
  extension-manifest-v2/src/classes/ConfData.js
  extension-manifest-v2/src/classes/PanelData.js
  extension-manifest-v2/src/modules/autoconsent.js
  extension-manifest-v2/webpack.config.js
  extension-manifest-v3/src/background/autoconsent.js
  extension-manifest-v3/src/manifest.chromium.json
  extension-manifest-v3/src/manifest.firefox.json
  extension-manifest-v3/src/manifest.safari-ios.json
  extension-manifest-v3/src/manifest.safari-macos.json
  extension-manifest-v3/src/notifications/opera-serp.js
  extension-manifest-v3/src/pages/autoconsent/index.html
  extension-manifest-v3/src/pages/autoconsent/index.js
  extension-manifest-v3/src/pages/settings/views/privacy.js
  extension-manifest-v3/src/store/options.js
  packages/ui/package.json
  packages/ui/src/modules/autoconsent/components/card.js
  packages/ui/src/modules/autoconsent/components/header.js
  packages/ui/src/modules/autoconsent/index.js
  packages/ui/src/modules/autoconsent/views/confirm.js
  packages/ui/src/modules/autoconsent/views/home.js
  packages/ui/src/modules/autoconsent/views/main.js
Labels: Type: Never-Consent, v8, v10, UI

#1498 Only show WTM stats link for the tracked domain
  packages/ui/src/modules/panel/components/stats.js
Labels: v10, UI

#1493 Release 10.2.13
  extension-manifest-v3/package.json
  extension-manifest-v3/xcode/Ghostery.xcodeproj/project.pbxproj
  package-lock.json
Labels: v10, Opera, Safari, release

#1490 Release 8.12.7
  extension-manifest-v2/src/classes/Account.js
Labels: Chrome, Firefox, Edge

#1505 Add contributor badge info to panel and settings page
  extension-manifest-v3/src/pages/panel/components/navigation-card.js
  extension-manifest-v3/src/pages/panel/views/navigation.js
  extension-manifest-v3/src/pages/settings/assets/contributor_badge.svg
  extension-manifest-v3/src/pages/settings/settings.js
  extension-manifest-v3/src/utils/api.js
  packages/ui/src/modules/global/components/action.js
  packages/ui/src/modules/global/components/icon.js
Labels: v10

#1501 Release 10.2.14
  extension-manifest-v3/package.json
  extension-manifest-v3/src/_locales/de/messages.json
  extension-manifest-v3/src/_locales/en/messages.json
  extension-manifest-v3/src/_locales/es/messages.json
  extension-manifest-v3/src/_locales/fr/messages.json
  extension-manifest-v3/src/_locales/it/messages.json
  extension-manifest-v3/src/_locales/ja/messages.json
  extension-manifest-v3/src/_locales/ko/messages.json
  extension-manifest-v3/src/_locales/pl/messages.json
  extension-manifest-v3/src/_locales/pt_BR/messages.json
  extension-manifest-v3/src/_locales/ru/messages.json
  extension-manifest-v3/src/_locales/zh_CN/messages.json
  extension-manifest-v3/src/_locales/zh_TW/messages.json
  extension-manifest-v3/src/pages/panel/views/navigation.js
  extension-manifest-v3/src/utils/api.js
  extension-manifest-v3/xcode/Ghostery.xcodeproj/project.pbxproj
  extension-manifest-v3/xcode/macOS (App)/Ghostery – Privacy Ad Blocker.entitlements
  extension-manifest-v3/xcode/macOS (Extension)/Ghostery – Privacy Ad Blocker.entitlements
  package-lock.json
Labels: Opera, Safari, release, Ghostery Browser

#1517 Fix Safari host permissions
  extension-manifest-v3/src/utils/api.js
Labels: v10, Safari

#1516 Release 10.2.15
  extension-manifest-v3/package.json
  extension-manifest-v3/xcode/Ghostery.xcodeproj/project.pbxproj
  package-lock.json
Labels: Opera, Safari, package

#1354 Simple custom filters editor
  extension-manifest-v2/package.json
  extension-manifest-v3/package.json
  extension-manifest-v3/scripts/download-engines/index.js
  extension-manifest-v3/scripts/download-engines/utils.js
  extension-manifest-v3/src/background/adblocker.js
  extension-manifest-v3/src/background/custom-filters.js
  extension-manifest-v3/src/background/dnr.js
  extension-manifest-v3/src/background/index.js
  extension-manifest-v3/src/pages/settings/components/custom-filters.js
  extension-manifest-v3/src/pages/settings/components/devtools.js
  extension-manifest-v3/src/pages/settings/index.js
  extension-manifest-v3/src/pages/settings/store/custom-filters-input.js
  extension-manifest-v3/src/utils/dnr-converter.js
  extension-manifest-v3/src/utils/engines.js
  package-lock.json
  packages/ui/package.json
  packages/ui/src/modules/panel/styles.css
  packages/ui/src/modules/settings/components/input.js
Labels: Type: Feature Enhancement, Type: Ad-Blocking, v10
