Repository ghostery/ghostery-extension, pull requests merged in 2024-04, with the labels that each got.

#1519 Adblocker preprocessor support
  extension-manifest-v2/package.json
  extension-manifest-v3/package.json
  extension-manifest-v3/src/pages/settings/components/custom-filters.js
  extension-manifest-v3/src/utils/engines.js
  package-lock.json
Labels: Type: Feature Enhancement, Type: Ad-Blocking, v8, v10

#1530 Fix Opera detection
  extension-manifest-v3/src/background/reporting/index.js
Labels: Type: Bug, Opera

#1531 Ghostery 10: staging setup
  extension-manifest-v3/package.json
  extension-manifest-v3/scripts/build.js
  extension-manifest-v3/scripts/download-engines/index.js
  extension-manifest-v3/scripts/download-engines/utils.js
  extension-manifest-v3/src/background/telemetry.js
  extension-manifest-v3/src/utils/api.js
  extension-manifest-v3/src/utils/engines.js
  package-lock.json
  packages/libs/src/index.js
  packages/libs/src/metrics.js
  packages/libs/src/urls.js
  packages/ui/package.json
  packages/ui/src/modules/onboarding/views/main.js
  packages/ui/src/modules/onboarding/views/privacy.js
  packages/ui/src/modules/onboarding/views/short/main.js
  packages/ui/src/modules/onboarding/views/short/outro-skip.js
  packages/ui/src/modules/panel/components/stats.js
Labels: v10

#1522 Release 10.2.16
  extension-manifest-v3/package.json
  extension-manifest-v3/scripts/download-engines/index.js
  extension-manifest-v3/src/_locales/de/messages.json
  extension-manifest-v3/src/_locales/en/messages.json
  extension-manifest-v3/src/_locales/es/messages.json
  extension-manifest-v3/src/_locales/fr/messages.json
  extension-manifest-v3/src/_locales/it/messages.json
  extension-manifest-v3/src/_locales/ja/messages.json
  extension-manifest-v3/src/_locales/ko/messages.json
  extension-manifest-v3/src/_locales/pl/messages.json
  extension-manifest-v3/src/_locales/pt_BR/messages.json
  extension-manifest-v3/src/_locales/ru/messages.json
  extension-manifest-v3/src/_locales/zh_CN/messages.json
  extension-manifest-v3/src/_locales/zh_TW/messages.json
  extension-manifest-v3/src/pages/settings/components/custom-filters.js
  extension-manifest-v3/xcode/Ghostery.xcodeproj/project.pbxproj
  package-lock.json
Labels: v10, Opera, Safari, package

#1544 Ghostery 8: fix for missing ghostery_id
  extension-manifest-v2/src/utils/matcher.js
Labels: Type: Bug, Chrome, Firefox, v8, Edge
