Repository ghostery/ghostery-extension, pull requests merged in 2024-11, with the labels that each got.

#2015 feat(options): Add support for managed storage
  scripts/build.js
  src/managed_storage.json
  src/manifest.chromium.json
  src/pages/onboarding/index.js
  src/pages/panel/components/managed.js
  src/pages/panel/views/main.js
  src/pages/panel/views/menu.js
  src/pages/panel/views/tracker-details.js
  src/pages/settings/index.js
  src/pages/trackers-preview/components/layout.js
  src/store/options.js
  src/ui/components/stats.js
Labels: package

#2046 feat(panel): add call for review notification
  src/pages/panel/components/menu-item.js
  src/pages/panel/components/notification.js
  src/pages/panel/store/notification.js
  src/ui/components/icon.js
  src/utils/browser-info.js
Labels: package

#2053 Release v10.4.13
  package-lock.json
  package.json
  src/_locales/de/messages.json
  src/_locales/en/messages.json
  src/_locales/es/messages.json
  src/_locales/fr/messages.json
  src/_locales/it/messages.json
  src/_locales/ja/messages.json
  src/_locales/ko/messages.json
  src/_locales/pl/messages.json
  src/_locales/pt_BR/messages.json
  src/_locales/ru/messages.json
  src/_locales/zh_CN/messages.json
  src/_locales/zh_TW/messages.json
  xcode/Ghostery.xcodeproj/project.pbxproj
Labels: package

#2067 fix(background): revert to background page for Safari 17.x
  eslint.config.js
  scripts/build.js
  src/background/index.html
  src/manifest.safari.json
Labels: Bug, Safari, iOS

#2066 Adblocker: fix $replace and service worker blocking
  src/background/adblocker.js
  src/background/custom-filters.js
  tests/e2e/spec/advanced.spec.js
Labels: Bug

#2071 Anti-Tracking: fix token telemetry
  package-lock.json
  package.json
Labels: Bug, Anti-Tracking

#2072 Release v10.4.15
  package-lock.json
  package.json
  xcode/Ghostery.xcodeproj/project.pbxproj
Labels: package

#2062 fix(sync): move options sync to background process
  src/background/index.js
  src/background/session.js
  src/background/sync.js
  src/pages/panel/index.js
  src/pages/settings/index.js
  src/pages/settings/views/account.js
  src/store/options.js
  src/utils/debounce.js
  src/utils/options-observer.js
Labels: package

#2087 Anti-Tracking: fix compatibility list
  package-lock.json
  package.json
Labels: Bug, Anti-Tracking

#2088 Release v10.4.16
  package-lock.json
  package.json
  src/_locales/fr/messages.json
  src/_locales/ko/messages.json
  xcode/Ghostery.xcodeproj/project.pbxproj
Labels: package
